# Generated by Django 6.0.1 on 2026-01-20 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(help_text='Porcentaje de descuento (ej: 15)'),
        ),
    ]
